### ISSUE TITLE
Error: No devices found

### ISSUE THREAD

**Issue by manojmukkamala** [DeakoLights/pydeako#1]
I am running the example shared in readme

```
import asyncio
from pydeako import discover

async def _discover():
    d = discover.DeakoDiscoverer()
    try:
        address = await d.get_address()
        print(f"Found deako device at {address}!")
    except discover.DevicesNotFoundException:
        print(f"Error: {e}")
        pass

if __name__ == "__main__":
    asyncio.run(_discover())
```

but it returns `Error: No devices found via _deako._tcp.local.`

FWIW - I can see my deako smart switch on wifi router device list and was able to successfully ping from the same device that threw the error when using pydeako.

Can someone help?

**Comment by Balake** [comment]
> I am running the example shared in readme
> 
> ```
> import asyncio
> from pydeako import discover
> 
> async def _discover():
>     d = discover.DeakoDiscoverer()
>     try:
>         address = await d.get_address()
>         print(f"Found deako device at {address}!")
>     except discover.DevicesNotFoundException:
>         print(f"Error: {e}")
>         pass
> 
> if __name__ == "__main__":
>     asyncio.run(_discover())
> ```
> 
> but it returns `Error: No devices found via _deako._tcp.local.`
> 
> FWIW - I can see my deako smart switch on wifi router device list and was able to successfully ping from the same device that threw the error when using pydeako.
> 
> Can someone help?

Hey there! I'm the author and back from vacation. There are a few things you can do:
1. Make sure you're on the same network as your deako devices
2. If this is running in a container, make sure your network mode is host in order to pass through mdns
3. Scan your network using a cli tool like `dns-sd` (I'm on macOS and this is available):

```
dns-sd -B _services._dns-sd._udp | grep deako 
13:52:37.621  Add        3  26 .                    _tcp.local.          _deako
13:52:37.621  Add        3  14 .                    _tcp.local.          _deako
```

The above command shows that there are deako devices advertising on my network. If you want specific deako devices, you can do: 
```
dns-sd -B _deako._tcp

Browsing for _deako._tcp
DATE: ---Mon 04 Dec 2023---
13:54:38.296  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
13:54:38.297  Add        3  26 local.               _deako._tcp.         231M001566002124
13:54:38.297  Add        3  14 local.               _deako._tcp.         231M001566002124
13:54:38.297  Add        3  26 local.               _deako._tcp.         231M001566001472
13:54:38.297  Add        3  14 local.               _deako._tcp.         231M001566001472
```

With that info above, if I run the sample in the readme via a file `test.py`, I get:

```
python test.py                               
Found deako device at 10.0.1.202:23!
```

Let me know if any of that works for you!

**Comment by manojmukkamala** [comment]
Thanks @Balake ! I think the issue is with my docker container running on a Mac OS host. `dns-sd` commands on host machine finds/prints the deako device however docker container cannot, even with `--privileged --net=host` flags.
When I run the `test.py` on a RaspberryPi, it found the device.

**Comment by manojmukkamala** [comment]
Hi again, Happy New Year!
I've resumed testing after holidays and ran into an issue, particularly with the second example from the documentation. 

```
import asyncio
from pydeako import deako, discover

async def _discover():
    client_name = "MyClient"
    d = discover.DeakoDiscoverer()
    deako_client = deako.Deako(d.get_address, client_name=client_name)

    await deako_client.connect()
    await deako_client.find_devices()

    devices = deako_client.get_devices()

    # turn on all devices
    for uuid in devices:
        await deako_client.control_device(uuid, True)

if __name__ == "__main__":
    asyncio.run(_discover())
```

and here is the error message:

```
2024-01-06 02:58:46.076 ERROR (MainThread) [pydeako.deako] Timeout attempting to connect. Trying again
2024-01-06 02:58:46.077 ERROR (MainThread) [pydeako.deako] Already attempting to connect
2024-01-06 02:58:46.077 ERROR (MainThread) [pydeako.deako] No connection to send data to
2024-01-06 02:58:56.087 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Deako for deako
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deako/__init__.py", line 33, in async_setup_entry
    await connection.find_devices()
  File "/usr/local/lib/python3.11/site-packages/pydeako/deako/_deako.py", line 130, in find_devices
    raise DeviceListTimeout()
pydeako.deako._deako.DeviceListTimeout
```

I've a smart-dimmer and a couple of smart-switches. Upon re-trying, I noticed I was able to turn on the smart-dimmer but no luck with smart switches. Let me know if I should share more info. Thanks!

Host: Raspberry Pi 4

**Comment by Balake** [comment]
> Hi again, Happy New Year! I've resumed testing after holidays and ran into an issue, particularly with the second example from the documentation.
> 
> ```
> import asyncio
> from pydeako import deako, discover
> 
> async def _discover():
>     client_name = "MyClient"
>     d = discover.DeakoDiscoverer()
>     deako_client = deako.Deako(d.get_address, client_name=client_name)
> 
>     await deako_client.connect()
>     await deako_client.find_devices()
> 
>     devices = deako_client.get_devices()
> 
>     # turn on all devices
>     for uuid in devices:
>         await deako_client.control_device(uuid, True)
> 
> if __name__ == "__main__":
>     asyncio.run(_discover())
> ```
> 
> and here is the error message:
> 
> ```
> Timeout attempting to connect. Trying again
> Already attempting to connect
> No connection to send data to
> Traceback (most recent call last):
>   File "/home/amoeba/nas/users/shared/homelab-test/deako/socket-client.py", line 19, in <module>
>     asyncio.run(_discover())
>   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/home/amoeba/nas/users/shared/homelab-test/deako/socket-client.py", line 10, in _discover
>     await deako_client.find_devices()
>   File "/home/amoeba/.local/lib/python3.11/site-packages/pydeako/deako/_deako.py", line 130, in find_devices
>     raise DeviceListTimeout()
> pydeako.deako._deako.DeviceListTimeout
> ```
> 
> I've a smart-dimmer and a couple of smart-switches. Upon re-trying, I noticed I was able to turn on the smart-dimmer but no luck with smart switches. Let me know if I should share more info. Thanks!
> 
> Host: Raspberry Pi 4

Hey there! Sorry for the late reply, but I've made some changes to this library around connection logic. It doesn't affect your particular error, but some other things are improved.

Your particular error indicates an issue with the device itself not returning any devices or not responding to the command for the device list, something that I don't think I can fix without logs from the device.

**Comment by manojmukkamala** [comment]
thanks! the latest version seems to have fixed my issue.

**Comment by Balake** [comment]
> thanks! the latest version seems to have fixed my issue.

Great, thanks for reporting back!
